# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

services:
  tbrd_ckan:
    container_name:  tbrd_ckan
    restart: unless-stopped
    build:
      context: ../../
      args:
          - CKAN_SITE_URL=${CKAN_SITE_URL}
          - CKAN_SITE_ROOT_PATH=${CKAN_SITE_ROOT_PATH}
    links:
      - tbrd_solr
      - tbrd_redis

    environment:
      # Defaults work with linked containers, change to use own SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://${CKAN_DATABASE_USER}:${CKAN_DATABASE_PASSWORD}@${CKAN_DATABASE_HOST}/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://${CKAN_DATABASE_USER}:${CKAN_DATABASE_PASSWORD}@${CKAN_DATABASE_HOST}/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://tbrd_solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://tbrd_redis:6379/1
      - CKAN_DATAPUSHER_URL=http://tbrd_datapusher:8800

      # sub-pathing config
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_SITE_ROOT_PATH=${CKAN_SITE_ROOT_PATH}

      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - DOI_EXT_PLUGIN=${DOI_EXT_PLUGIN}
      - DOI_EXT_ACCOUNT_NAME=${DOI_EXT_ACCOUNT_NAME}
      - DOI_EXT_ACCOUNT_PASSWORD=${DOI_EXT_ACCOUNT_PASSWORD}
      - DOI_EXT_PREFIX=${DOI_EXT_PREFIX}
      - DOI_EXT_PUBLISHER=${DOI_EXT_PUBLISHER}
      - DOI_EXT_TEST_MODE=${DOI_EXT_TEST_MODE}

      # Database auth
      - CKAN_DATABASE_HOST=${CKAN_DATABASE_HOST}
      - CKAN_DATABASE_USER=${CKAN_DATABASE_USER}
      - CKAN_DATABASE_PASSWORD=${CKAN_DATABASE_PASSWORD}
    networks:
      - tbrd_network

    volumes:
      - tbrd_ckan_config:/etc/ckan
      - tbrd_ckan_home:/usr/lib/ckan
      - tbrd_ckan_store:/var/lib/ckan

  tbrd_datapusher:
    restart: unless-stopped
    container_name:  tbrd_datapusher
    image: clementmouchet/datapusher

  tbrd_solr:
    restart: unless-stopped
    container_name: tbrd_solr
    build:
      context: ../../
      dockerfile: contrib/docker/solr/Dockerfile
    volumes:
      - tbrd_solr_data:/opt/solr/server/solr/ckan/data
    networks:
      - tbrd_network

  tbrd_redis:
    restart: unless-stopped
    container_name: tbrd_redis
    image: redis:latest
    networks:
      - tbrd_network

networks: 
  tbrd_network:
    external: true

volumes:
  tbrd_ckan_config:
  tbrd_ckan_home:
  tbrd_ckan_store:
  tbrd_solr_data:
